apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: us-central1-docker.pkg.dev/warm-tokenizer-384309/demo/demo:1.0.0
          command: ["echo 'running here'"]
      restartPolicy: Never
