apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: demo-app
        spec:
          containers:
            - name: demo-container
              image: us-central1-docker.pkg.dev/warm-tokenizer-384309/demo/demo:1.0.0
              command: ["/go_hw"]
          restartPolicy: OnFailure
